library(tidyverse)
library(plotly)
library(lubridate)
library(shiny)
library(shinyjs)
#library(plyr)
#library(dplyr)

# Always get full stack trace
options(shiny.fullstacktrace=TRUE)
# Show milliseconds on timestamps
options("digits.secs"=6)
# Increase maximum file upload size for CSV files to 50MB.
options(shiny.maxRequestSize=50*1024^2)

source("modules/csv_upload_module.R", local = T)
source("modules/db_select_module.R", local = T)
source("modules/db_session_row_module.R", local = T)
source("modules/data_selection_summary_module.R", local = T)
source("modules/player_overview_module.R", local = T)
source("modules/individual_game_performance_module.R", local = T)
source("modules/game_timeline_module.R", local = T)
source("modules/plot_scatter_timeline_module.R", local = T)
source("utils/loadrawdata.R", local = T)
source("utils/loaddbdata.R", local = T)
source("utils/errorhandling.R", local = T)
source("vis/vis_timeline_whack.R", local = T)
source("vis/vis_whackgrid.R", local = T)
source("vis/vis_moletable.R", local = T)
source("vis/vis_eyeplot.R", local = T)
source("vis/vis_motorspace.R", local = T)
source("vis/vis_directiontable.R", local = T)